/**
 * API kataloğu — route.ts dosyalarından türetilmiş tek kaynak.
 * api-referans sayfası bu listeyi kullanır; yeni endpoint eklenince burayı güncelleyin.
 */

export type ApiEndpoint = {
  method: string;
  path: string;
  title: string;
  desc: string;
  group: string;
  request?: string | null;
  response?: string;
  responses: { code: string; desc: string }[];
  uiLink?: string;
  tags?: string[];
};

export const API_GROUPS = [
  "Lisans",
  "Uzak Modüller",
  "Firma Oto-Modüller",
  "Komut Kuyruğu",
  "Cihaz & Nabız",
  "Modül Çıktıları",
  "İndirmeler",
  "Yapılandırma",
  "Gerçek Zamanlı",
] as const;

export const API_ENDPOINTS: ApiEndpoint[] = [
  // ── Lisans ──
  {
    group: "Lisans",
    method: "GET",
    path: "/license/{mac}/",
    title: "Lisans Sorgula",
    desc: "MAC adresine göre lisans kaydını döndürür. VBA getLicense sonrası doğrulama.",
    request: null,
    response: `{\n  "success": true,\n  "data": {\n    "macAdresi": "04:EC:D8:AE:C0:4A",\n    "license": "true",\n    "firmaAdi": "EPRON",\n    "userAdi": "Onur",\n    "updatedAt": "2026-06-22T12:00:00.000Z"\n  }\n}`,
    responses: [
      { code: "200", desc: "Kayıt bulundu" },
      { code: "200 (success:false)", desc: "MAC bulunamadı" },
    ],
    uiLink: "/lisanslar",
  },
  {
    group: "Lisans",
    method: "POST",
    path: "/license/",
    title: "Lisans Kayıt / Güncelleme",
    desc: "Yeni cihaz kaydı veya güncelleme. İhlal tespitinde ihlal:true döner.",
    request: `{\n  "macAdresi": "04:EC:D8:AE:C0:4A",\n  "firmaAdi": "EPRON",\n  "userAdi": "Onur",\n  "dosyaAdi": "teklif.xlam"\n}`,
    response: `{\n  "success": true,\n  "ihlal": false,\n  "data": { "license": "false", "firmaAdi": "EPRON" }\n}`,
    responses: [
      { code: "201", desc: "Yeni kayıt" },
      { code: "200", desc: "Güncelleme" },
    ],
    uiLink: "/lisanslar",
  },
  {
    group: "Lisans",
    method: "PATCH",
    path: "/license/{mac}/",
    title: "Lisans Aktif/Pasif",
    desc: "Dashboard üzerinden tek lisansı aç/kapat.",
    request: `{ "license": "true" }`,
    response: `{ "success": true, "data": { "license": "true" } }`,
    responses: [
      { code: "200", desc: "Güncellendi" },
      { code: "404", desc: "MAC bulunamadı" },
    ],
    uiLink: "/lisanslar",
  },
  {
    group: "Lisans",
    method: "PATCH",
    path: "/license/bulk/",
    title: "Toplu Lisans Aç/Kapat",
    desc: "Birden fazla MAC için toplu aktivasyon.",
    request: `{\n  "macs": ["04:EC:D8:AE:C0:4A"],\n  "action": "activate"\n}`,
    response: `{ "success": true, "affected": 1, "action": "activate" }`,
    responses: [{ code: "200", desc: "Toplu işlem tamam" }],
    uiLink: "/lisanslar",
  },

  // ── Uzak Modüller ──
  {
    group: "Uzak Modüller",
    method: "POST",
    path: "/module/",
    title: "Uzak VBA Modülü Al",
    desc: "RunRemoteCode — methodName ile VBA kaynak kodunu döndürür.",
    request: `{ "methodName": "GetCpuUsage" }`,
    response: `{ "success": true, "code": "Public Function DynamicFunc..." }`,
    responses: [
      { code: "200", desc: "Kod döndürüldü" },
      { code: "404", desc: "Modül yok" },
    ],
    uiLink: "/moduller",
  },
  {
    group: "Uzak Modüller",
    method: "GET",
    path: "/modules/",
    title: "Modül Listesi",
    desc: "Tüm uzak modülleri listeler; eksikler JSON'dan senkronize edilir.",
    request: null,
    response: `{ "success": true, "data": [{ "methodName": "...", "category": "donanim" }] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/moduller",
  },
  {
    group: "Uzak Modüller",
    method: "POST",
    path: "/modules/",
    title: "Modül Ekle/Güncelle",
    desc: "Yeni modül upsert veya mevcut modülü günceller.",
    request: `{\n  "methodName": "SelamTest",\n  "description": "...",\n  "category": "genel",\n  "code": "Public Function...",\n  "active": true\n}`,
    response: `{ "success": true, "data": { "methodName": "SelamTest" } }`,
    responses: [{ code: "201", desc: "Kaydedildi" }],
    uiLink: "/moduller",
  },
  {
    group: "Uzak Modüller",
    method: "PATCH",
    path: "/modules/{id}/",
    title: "Modül Güncelle",
    desc: "ID ile modül alanlarını günceller.",
    request: `{ "description": "...", "active": false }`,
    response: `{ "success": true, "data": { ... } }`,
    responses: [{ code: "200", desc: "Güncellendi" }],
    uiLink: "/moduller",
  },
  {
    group: "Uzak Modüller",
    method: "DELETE",
    path: "/modules/{id}/",
    title: "Modül Sil",
    desc: "Modülü veritabanından siler.",
    request: null,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Silindi" }],
    uiLink: "/moduller",
  },

  // ── Firma Oto-Modüller ──
  {
    group: "Firma Oto-Modüller",
    method: "GET",
    path: "/auto-start/{mac}/",
    title: "Excel Açılış Modülleri",
    desc: "MAC'e göre firma bazlı otomatik çalışacak modül listesi (runOnce, delaySeconds).",
    request: null,
    response: `{\n  "success": true,\n  "data": {\n    "firmaAdi": "EPRON",\n    "modules": [\n      { "methodName": "HeartbeatPing", "order": 2, "runOnce": true }\n    ]\n  }\n}`,
    responses: [{ code: "200", desc: "Modül listesi" }],
    uiLink: "/firma-modulleri",
  },
  {
    group: "Firma Oto-Modüller",
    method: "GET",
    path: "/firm-modules/",
    title: "Firma Konfig Listesi",
    desc: "Tüm firma otomatik modül tanımlarını döndürür.",
    request: null,
    response: `{ "success": true, "data": [...] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/firma-modulleri",
  },
  {
    group: "Firma Oto-Modüller",
    method: "POST",
    path: "/firm-modules/",
    title: "Firma Ekle",
    desc: "Yeni firma otomatik modül kaydı oluşturur.",
    request: `{ "firmaAdi": "EPRON", "description": "..." }`,
    response: `{ "success": true, "data": { ... } }`,
    responses: [{ code: "201", desc: "Oluşturuldu" }],
    uiLink: "/firma-modulleri",
  },
  {
    group: "Firma Oto-Modüller",
    method: "PATCH",
    path: "/firm-modules/{firmaAdi}/",
    title: "Firma Modül Düzenle",
    desc: "Modül ekle/çıkar, sırala, runOnce ve gecikme ayarla.",
    request: `{\n  "addModule": { "methodName": "InstallCommandQueue", "order": 3, "runOnce": true, "delaySeconds": 3 }\n}`,
    response: `{ "success": true, "data": { ... } }`,
    responses: [{ code: "200", desc: "Güncellendi" }],
    uiLink: "/firma-modulleri",
  },

  // ── Komut Kuyruğu ──
  {
    group: "Komut Kuyruğu",
    method: "GET",
    path: "/commands/pending/{mac}/",
    title: "Bekleyen Komut Al",
    desc: "InstallCommandQueue poller — en eski pending komutu running yapar ve döner.",
    request: null,
    response: `{ "success": true, "data": { "id": 12, "moduleName": "GetDiskInfo", "status": "running" } }`,
    responses: [
      { code: "200", desc: "Komut var" },
      { code: "200 (data:null)", desc: "Kuyruk boş" },
    ],
    uiLink: "/komutlar",
  },
  {
    group: "Komut Kuyruğu",
    method: "PATCH",
    path: "/commands/{id}/",
    title: "Komut Sonucu Bildir",
    desc: "VBA komut tamamlandığında done/error olarak günceller.",
    request: `{\n  "status": "done",\n  "result": "OK",\n  "errorMsg": ""\n}`,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Güncellendi" }],
    uiLink: "/komutlar",
  },
  {
    group: "Komut Kuyruğu",
    method: "GET",
    path: "/commands/",
    title: "Komut Listesi",
    desc: "Dashboard — mac ve status ile filtreleme.",
    request: null,
    response: `{ "success": true, "data": [{ "id": 1, "status": "pending" }] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/komutlar",
    tags: ["query: mac, status, limit"],
  },
  {
    group: "Komut Kuyruğu",
    method: "POST",
    path: "/commands/",
    title: "Komut Gönder",
    desc: "Dashboard'dan istemciye uzak modül komutu kuyruğa ekler.",
    request: `{\n  "mac": "04:EC:D8:AE:C0:4A",\n  "moduleName": "GetCpuUsage",\n  "param": ""\n}`,
    response: `{ "success": true, "data": { "id": 15, "status": "pending" } }`,
    responses: [{ code: "201", desc: "Kuyruğa eklendi" }],
    uiLink: "/komutlar",
  },
  {
    group: "Komut Kuyruğu",
    method: "DELETE",
    path: "/commands/?id={id}",
    title: "Komut Sil",
    desc: "Bekleyen veya takılı komutu siler.",
    request: null,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Silindi" }],
    uiLink: "/komutlar",
  },

  // ── Cihaz & Nabız ──
  {
    group: "Cihaz & Nabız",
    method: "POST",
    path: "/heartbeat/",
    title: "Heartbeat Ping",
    desc: "TeklifAgent / HeartbeatPing — MAC, hostname, Excel sürümü.",
    request: `{\n  "mac": "04:EC:D8:AE:C0:4A",\n  "hostname": "SERCAN",\n  "user": "Cang",\n  "excelVersion": "16.0"\n}`,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Kaydedildi" }],
    uiLink: "/heartbeats",
  },
  {
    group: "Cihaz & Nabız",
    method: "GET",
    path: "/heartbeat/",
    title: "Heartbeat Listesi",
    desc: "Nabız izleme sayfası — tüm cihazların son görülme zamanı.",
    request: null,
    response: `{ "success": true, "data": [{ "mac": "...", "last_seen": "..." }] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/heartbeats",
  },
  {
    group: "Cihaz & Nabız",
    method: "POST",
    path: "/device-info/",
    title: "Cihaz Bilgisi Gönder",
    desc: "CollectDeviceInfoServer — donanım anlık görüntüsü.",
    request: `{\n  "mac": "04:EC:D8:AE:C0:4A",\n  "hostname": "SERCAN",\n  "data": { "cpu": "...", "ram": "16 GB" }\n}`,
    response: `{ "success": true, "message": "..." }`,
    responses: [{ code: "200", desc: "Kaydedildi" }],
    uiLink: "/cihazlar",
  },
  {
    group: "Cihaz & Nabız",
    method: "GET",
    path: "/device-info/",
    title: "Cihaz Bilgisi Listesi",
    desc: "Tüm cihaz snapshot'ları veya ?mac= ile tek cihaz.",
    request: null,
    response: `{ "success": true, "data": [{ "mac": "...", "data": { ... } }] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/cihazlar",
    tags: ["query: mac"],
  },

  // ── Modül Çıktıları ──
  {
    group: "Modül Çıktıları",
    method: "POST",
    path: "/module-output/",
    title: "Modül Çıktısı Gönder",
    desc: "GetCpuUsage, GetDiskInfo vb. — JSON çıktıyı sunucuya yazar.",
    request: `{\n  "mac": "04:EC:D8:AE:C0:4A",\n  "moduleName": "GetCpuUsage",\n  "output": { "CPU 1": "45 %" }\n}`,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Kaydedildi" }],
    uiLink: "/modul-ciktilari",
  },
  {
    group: "Modül Çıktıları",
    method: "GET",
    path: "/module-output/",
    title: "Çıktı Listesi",
    desc: "mac, moduleName, limit ile filtreleme.",
    request: null,
    response: `{ "success": true, "data": [...] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/modul-ciktilari",
  },
  {
    group: "Modül Çıktıları",
    method: "GET",
    path: "/module-output/summary/",
    title: "Çıktı Özeti",
    desc: "Modül başına toplam çalıştırma ve son çalışma zamanı.",
    request: null,
    response: `{ "success": true, "data": [{ "moduleName": "GetCpuUsage", "count": 5 }] }`,
    responses: [{ code: "200", desc: "Özet" }],
    uiLink: "/modul-ciktilari",
  },
  {
    group: "Modül Çıktıları",
    method: "DELETE",
    path: "/module-output/{id}/",
    title: "Çıktı Sil",
    desc: "Tek bir modül çıktı kaydını siler.",
    request: null,
    response: `{ "success": true }`,
    responses: [{ code: "200", desc: "Silindi" }],
    uiLink: "/modul-ciktilari",
  },

  // ── İndirmeler ──
  {
    group: "İndirmeler",
    method: "POST",
    path: "/download/teklif/",
    title: "Eklenti İndir (.xlam)",
    desc: "Lisanslı kullanıcıya teklif.xlam binary indirir.",
    request: `{ "macAdresi": "04:EC:D8:AE:C0:4A" }`,
    response: "(binary .xlam)",
    responses: [
      { code: "200", desc: "Dosya" },
      { code: "403", desc: "Lisans pasif" },
    ],
  },
  {
    group: "İndirmeler",
    method: "GET",
    path: "/download/ihlal/",
    title: "İhlal Dosyası (.xlsm)",
    desc: "Lisans ihlali tespitinde getLicense tarafından indirilir.",
    request: null,
    response: "(binary ihlal.xlsm)",
    responses: [{ code: "200", desc: "Dosya" }],
  },
  {
    group: "İndirmeler",
    method: "GET",
    path: "/download/poll-host/",
    title: "Poll Host (.xlsm)",
    desc: "Komut kuyruğu için TeklifPollHost workbook.",
    request: null,
    response: "(binary TeklifPollHost.xlsm)",
    responses: [{ code: "200", desc: "Dosya" }],
  },
  {
    group: "İndirmeler",
    method: "GET",
    path: "/agent/download/",
    title: "TeklifAgent İndir",
    desc: "Agent DLL veya EXE. Query: arch=x64|x86, file=dll|exe",
    request: null,
    response: "(binary TeklifAgent.exe / .dll)",
    responses: [{ code: "200", desc: "Binary" }],
    tags: ["query: arch, file"],
  },

  // ── Yapılandırma ──
  {
    group: "Yapılandırma",
    method: "GET",
    path: "/registry-settings/",
    title: "Registry Ayarları JSON",
    desc: "ImportRegistrySettings modülü — ilk kurulum varsayılanları.",
    request: null,
    response: `{ "ilhan": { "Settings": { ... } } }`,
    responses: [
      { code: "200", desc: "JSON" },
      { code: "404", desc: "Dosya yok" },
    ],
  },
  {
    group: "Yapılandırma",
    method: "GET",
    path: "/proposals/",
    title: "Modül Önerileri Durumu",
    desc: "module-proposals.md + dll önerileri ile Neon modules tablosu karşılaştırması.",
    request: null,
    response: `{ "success": true, "data": { "implemented": 100, "planned": 400, "items": [...] } }`,
    responses: [{ code: "200", desc: "Özet" }],
    uiLink: "/oneriler",
  },

  // ── Gerçek Zamanlı ──
  {
    group: "Gerçek Zamanlı",
    method: "GET",
    path: "/events/",
    title: "SSE — Canlı Güncelleme",
    desc: "Server-Sent Events; yeni lisans logu gelince dashboard yenilenir.",
    request: null,
    response: "event: update\\ndata: { latestLogId, ts }",
    responses: [{ code: "200", desc: "text/event-stream" }],
    uiLink: "/",
    tags: ["sse"],
  },
  {
    group: "Cihaz & Nabız",
    method: "GET|POST|DELETE",
    path: "/folder-watch/",
    title: "Klasör İzleme Olayları",
    desc: "WatchFolderServer — C:\\ değişiklik bildirimleri.",
    request: `{\n  "mac": "04:EC:D8:AE:C0:4A",\n  "folderPath": "C:\\\\",\n  "eventType": "created",\n  "fileName": "yeni.txt"\n}`,
    response: `{ "success": true, "data": [...] }`,
    responses: [{ code: "200", desc: "OK" }],
    uiLink: "/klasor-izleme",
  },
  {
    group: "Cihaz & Nabız",
    method: "GET",
    path: "/activity/",
    title: "Birleşik Aktivite Logu",
    desc: "Lisans, heartbeat, modül, komut, klasör ve dashboard olaylarını tek listede döner.",
    request: null,
    response: `{ "success": true, "data": [{ "category": "heartbeat", "title": "..." }] }`,
    responses: [{ code: "200", desc: "Liste" }],
    uiLink: "/loglar",
    tags: ["query: category, limit, mac"],
  },
];

export function getApiCatalogStats() {
  return {
    total: API_ENDPOINTS.length,
    groups: API_GROUPS.length,
    withUi: API_ENDPOINTS.filter((e) => e.uiLink).length,
  };
}
